spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/springboot-microservices-realm/protocol/openid-connect/certs      
      

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
  file:
    name : /Users/mani/Documents/Projects/MICROSERVICES-2025/logs/app.log
